In [1]:
import keras as ks
import tensorflow as tf
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer

/home/pandoora/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [85]:
einkommen = pd.read_csv("einkommen.train")

In [86]:
# changing index cols with 
einkommen.columns = ['Age', 'Employment', 'Weighting factor', 'Level of education', 
                'Schooling/training period', 'Marital status', 'Employment area', 'Partnership', 
                'Ethnicity', 'Gender', 'Gains on financial assets', 'Losses on financial assets', 
                'Weekly working time', 'Country of birth','Income'] 

In [87]:
einkommen.columns

Index(['Age', 'Employment', 'Weighting factor', 'Level of education',
       'Schooling/training period', 'Marital status', 'Employment area',
       'Partnership', 'Ethnicity', 'Gender', 'Gains on financial assets',
       'Losses on financial assets', 'Weekly working time', 'Country of birth',
       'Income'],
      dtype='object')

In [88]:
einkommen.head()

Age         Employment  Weighting factor Level of education  \
0   50   Self-emp-not-inc             83311          Bachelors   
1   38            Private            215646            HS-grad   
2   53            Private            234721               11th   
3   28            Private            338409          Bachelors   
4   37            Private            284582            Masters   

   Schooling/training period       Marital status     Employment area  \
0                         13   Married-civ-spouse     Exec-managerial   
1                          9             Divorced   Handlers-cleaners   
2                          7   Married-civ-spouse   Handlers-cleaners   
3                         13   Married-civ-spouse      Prof-specialty   
4                         14   Married-civ-spouse     Exec-managerial   

      Partnership Ethnicity   Gender  Gains on financial assets  \
0         Husband     White     Male                          0   
1   Not-in-family     White     Male                          0   
2         Husband     Black     Male                          0   
3            Wife     Black   Female                          0   
4            Wife     White   Female                          0   

   Losses on financial assets  Weekly working time Country of birth  Income  
0                           0                   13    United-States   <=50K  
1                           0                   40    United-States   <=50K  
2                           0                   40    United-States   <=50K  
3                           0                   40             Cuba   <=50K  
4                           0                   40    United-States   <=50K

In [89]:
set1 = einkommen[:4999]

In [82]:
set1["Gender"] = list(map(lambda a: 1 if a == "Male" else 0, set1["Gender"]  )) 

/home/pandoora/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [91]:
print(set1.groupby(['Gender'])[['Gender']].count())

         Gender
Gender         
 Female    1629
 Male      3370


In [59]:
set1.loc[:,'Gender'].unique()    

array([' Male', ' Female'], dtype=object)

In [62]:
set1

Age         Employment  Weighting factor Level of education  \
0      50   Self-emp-not-inc             83311          Bachelors   
1      38            Private            215646            HS-grad   
2      53            Private            234721               11th   
3      28            Private            338409          Bachelors   
4      37            Private            284582            Masters   
5      49            Private            160187                9th   
6      52   Self-emp-not-inc            209642            HS-grad   
7      31            Private             45781            Masters   
8      42            Private            159449          Bachelors   
9      37            Private            280464       Some-college   
10     30          State-gov            141297          Bachelors   
11     23            Private            122272          Bachelors   
12     32            Private            205019         Assoc-acdm   
13     40            Private            121772          Assoc-voc   
14     34            Private            245487            7th-8th   
15     25   Self-emp-not-inc            176756            HS-grad   
16     32            Private            186824            HS-grad   
17     38            Private             28887               11th   
18     43   Self-emp-not-inc            292175            Masters   
19     40            Private            193524          Doctorate   
20     54            Private            302146            HS-grad   
21     35        Federal-gov             76845                9th   
22     43            Private            117037               11th   
23     59            Private            109015            HS-grad   
24     56          Local-gov            216851          Bachelors   
25     19            Private            168294            HS-grad   
26     54                  ?            180211       Some-college   
27     39            Private            367260            HS-grad   
28     49            Private            193366            HS-grad   
29     23          Local-gov            190709         Assoc-acdm   
...   ...                ...               ...                ...   
4969   51                  ?            203953            HS-grad   
4970   46          State-gov             29696            HS-grad   
4971   30            Private            315640          Doctorate   
4972   37            Private            632613               10th   
4973   56            Private            282023        Prof-school   
4974   29            Private             77760            HS-grad   
4975   46   Self-emp-not-inc            148599            Masters   
4976   55            Private            414994            HS-grad   
4977   45            Private            339863          Bachelors   
4978   34            Private            499249            HS-grad   
4979   45                  ?            144354                9th   
4980   41            Private            252058          Bachelors   
4981   22                  ?             99543       Some-college   
4982   34            Private            117963        Prof-school   
4983   27            Private            194652            HS-grad   
4984   29            Private            299705       Some-college   
4985   19        Federal-gov             27433               12th   
4986   47          Local-gov             39986          Bachelors   
4987   43       Self-emp-inc            135342       Some-college   
4988   52            Private            270142          Assoc-voc   
4989   33   Self-emp-not-inc            118267         Assoc-acdm   
4990   29            Private            266043                9th   
4991   23            Private             35633            HS-grad   
4992   23            Private             74568       Some-college   
4993   39            Private            214816          Bachelors   
4994   43            Private            222971            5th-6th   
4995

In [57]:
set1.iloc[:,-5].unique()  

array([    0, 14084,  5178,  5013,  2407, 14344, 15024,  7688, 34095,
        4064,  4386,  7298,  1409,  3674,  1055,  3464,  2050,  2176,
        2174,   594, 20051,  6849,  4101,  1111,  8614,  3411,  2597,
       25236,  4650,  9386,  2463,  3103, 10605,  2964,  3325,  2580,
        3471,  4865, 99999,  6514,  1471,  2329,  2105,  2885, 25124,
       10520,  2202,  2961, 27828,  6767,  2228,  1506, 13550,  2635,
        5556,  4787,  3781,  3137,  3818,  3942,   914,   401,  2829,
        2977,  4934,  2062,  2354,  5455, 15020,  1424,  3273, 22040,
        4416,  3908, 10566,   991,  4931,  1086,  7430,  6497,   114,
        7896,  2346])

In [43]:
pd.get_dummies(einkommen,prefix=['Level of education'])

ValueError: Length of 'prefix' (1) did not match the length of the columns being encoded (9).

In [61]:
set1

Age         Employment  Weighting factor Level of education  \
0      50   Self-emp-not-inc             83311          Bachelors   
1      38            Private            215646            HS-grad   
2      53            Private            234721               11th   
3      28            Private            338409          Bachelors   
4      37            Private            284582            Masters   
5      49            Private            160187                9th   
6      52   Self-emp-not-inc            209642            HS-grad   
7      31            Private             45781            Masters   
8      42            Private            159449          Bachelors   
9      37            Private            280464       Some-college   
10     30          State-gov            141297          Bachelors   
11     23            Private            122272          Bachelors   
12     32            Private            205019         Assoc-acdm   
13     40            Private            121772          Assoc-voc   
14     34            Private            245487            7th-8th   
15     25   Self-emp-not-inc            176756            HS-grad   
16     32            Private            186824            HS-grad   
17     38            Private             28887               11th   
18     43   Self-emp-not-inc            292175            Masters   
19     40            Private            193524          Doctorate   
20     54            Private            302146            HS-grad   
21     35        Federal-gov             76845                9th   
22     43            Private            117037               11th   
23     59            Private            109015            HS-grad   
24     56          Local-gov            216851          Bachelors   
25     19            Private            168294            HS-grad   
26     54                  ?            180211       Some-college   
27     39            Private            367260            HS-grad   
28     49            Private            193366            HS-grad   
29     23          Local-gov            190709         Assoc-acdm   
...   ...                ...               ...                ...   
4969   51                  ?            203953            HS-grad   
4970   46          State-gov             29696            HS-grad   
4971   30            Private            315640          Doctorate   
4972   37            Private            632613               10th   
4973   56            Private            282023        Prof-school   
4974   29            Private             77760            HS-grad   
4975   46   Self-emp-not-inc            148599            Masters   
4976   55            Private            414994            HS-grad   
4977   45            Private            339863          Bachelors   
4978   34            Private            499249            HS-grad   
4979   45                  ?            144354                9th   
4980   41            Private            252058          Bachelors   
4981   22                  ?             99543       Some-college   
4982   34            Private            117963        Prof-school   
4983   27            Private            194652            HS-grad   
4984   29            Private            299705       Some-college   
4985   19        Federal-gov             27433               12th   
4986   47          Local-gov             39986          Bachelors   
4987   43       Self-emp-inc            135342       Some-college   
4988   52            Private            270142          Assoc-voc   
4989   33   Self-emp-not-inc            118267         Assoc-acdm   
4990   29            Private            266043                9th   
4991   23            Private             35633            HS-grad   
4992   23            Private             74568       Some-college   
4993   39            Private            214816          Bachelors   
4994   43            Private            222971            5th-6th   
4995

In [3]:
def one_hot(data, colname):
    temp = data.loc[:,colname].unique()
    dictionary = dict((name,i) for i,name in enumerate(temp) if "?" != name and " ?" != name)
    data[colname] = data[colname].map(dictionary)
    return data,dictionary

In [4]:
liste1 = ["d","d","mendel"," ?", "sdfa"]
liste1

['d', 'd', 'mendel', ' ?', 'sdfa']

In [5]:
dict((name,i) for i,name in enumerate(liste1) if "?" != name and " ?" != name)

{'d': 1, 'mendel': 2, 'sdfa': 4}

In [6]:
one_hot(einkommen,"Employment")

NameError: name 'einkommen' is not defined

In [93]:
einkommen.loc[:,"Employment"].unique()

array([ 0.,  1.,  2.,  3.,  4., nan,  6.,  7.,  8.])

In [9]:
type(einkommen)

pandas.core.frame.DataFrame

In [23]:
y

array([' <=50K', ' >50K', ' ?'], dtype=object)

In [8]:
einkommen = pd.read_csv("einkommen.train")
# changing index cols with 
einkommen.columns = ['Age', 'Employment', 'Weighting factor', 'Level of education', 
                'Schooling/training period', 'Marital status', 'Employment area', 'Partnership', 
                'Ethnicity', 'Gender', 'Gains on financial assets', 'Losses on financial assets', 
                'Weekly working time', 'Country of birth','Income'] 


einkommen['Gender'] = einkommen['Gender'].map({' Female': 1, ' Male': 0})

list_of_dictionarys = {}

einkommen, list_of_dictionarys['Ethnicity']           = one_hot(einkommen, "Ethnicity")
einkommen, list_of_dictionarys['Partnership']         = one_hot(einkommen, "Partnership")
einkommen, list_of_dictionarys['Employment']          = one_hot(einkommen, "Employment")
einkommen, list_of_dictionarys['Level of education']  = one_hot(einkommen, "Level of education")
einkommen, list_of_dictionarys['Marital status']      = one_hot(einkommen, "Marital status")
einkommen, list_of_dictionarys['Employment area']     = one_hot(einkommen, "Employment area")
einkommen, list_of_dictionarys['Country of birth']    = one_hot(einkommen, "Country of birth")
einkommen, list_of_dictionarys['Income']    = one_hot(einkommen, "Income")

In [133]:
#einkommen.columns

In [242]:
[list_of_dictionarys[i] for i in list_of_dictionarys] 

[{' White': 0,
  ' Black': 1,
  ' Asian-Pac-Islander': 2,
  ' Amer-Indian-Eskimo': 3,
  ' Other': 4},
 {' Husband': 0,
  ' Not-in-family': 1,
  ' Wife': 2,
  ' Own-child': 3,
  ' Unmarried': 4,
  ' Other-relative': 5},
 {' Self-emp-not-inc': 0,
  ' Private': 1,
  ' State-gov': 2,
  ' Federal-gov': 3,
  ' Local-gov': 4,
  ' ?': 5,
  ' Self-emp-inc': 6,
  ' Without-pay': 7,
  ' Never-worked': 8},
 {' Bachelors': 0,
  ' HS-grad': 1,
  ' 11th': 2,
  ' Masters': 3,
  ' 9th': 4,
  ' Some-college': 5,
  ' Assoc-acdm': 6,
  ' Assoc-voc': 7,
  ' 7th-8th': 8,
  ' Doctorate': 9,
  ' Prof-school': 10,
  ' 5th-6th': 11,
  ' 10th': 12,
  ' 1st-4th': 13,
  ' Preschool': 14,
  ' 12th': 15},
 {' Married-civ-spouse': 0,
  ' Divorced': 1,
  ' Married-spouse-absent': 2,
  ' Never-married': 3,
  ' Separated': 4,
  ' Married-AF-spouse': 5,
  ' Widowed': 6},
 {' Exec-managerial': 0,
  ' Handlers-cleaners': 1,
  ' Prof-specialty': 2,
  ' Other-service': 3,
  ' Adm-clerical': 4,
  ' Sales': 5,
  ' Craft-repair

In [15]:
einkommen.head(3)

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   

         Adm-clerical   Not-in-family   White   Male   2174   0   40  \
0     Exec-managerial         Husband   White   Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White   Male      0   0   40   
2   Handlers-cleaners         Husband   Black   Male      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K

In [16]:
einkommen.loc[:,"Income"].unique()

KeyError: 'the label [Income] is not in the [columns]'

In [6]:
ein_train = einkommen.iloc[:4999,:]
ein_pred = einkommen.iloc[4999:,:]

In [7]:
#Dataframe
dataset = pd.DataFrame(ein_train)

In [8]:
data = dataset.values

In [9]:
sourcevars = data[:,:-1] #all columns except the last one
targetvar = data[:,len(data[0])-1] #only the last column

In [10]:
sourcevars.shape

(4999, 14)

In [11]:
targetvar.shape

(4999,)

In [13]:
sourcevars.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [63]:
X_train, X_test, y_train, y_test = train_test_split(sourcevars, targetvar)

In [64]:
X_train.shape

(22499, 14)

In [49]:
from sklearn.model_selection import train_test_split 

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
X_train, X_test, y_train, y_test = train_test_split(sourcevars, targetvar, test_size=0.3, random_state=1) 

In [54]:
X_train[2,:]

array([28, ' Private', 183175, ' Some-college', 10, ' Divorced',
       ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40,
       ' United-States'], dtype=object)

In [48]:
clf = DecisionTreeClassifier(random_state=0)

clf = clf.fit(sourcevars,targetvar)

ValueError: could not convert string to float: ' Self-emp-not-inc'

In [34]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(clf, sourcevars, targetvar, cv=10)

/home/pandoora/anaconda3/envs/mi/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


ValueError: could not convert string to float: ' Private'

In [ ]:
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
...                             
...
array([ 1.     ,  0.93...,  0.86...,  0.93...,  0.93...,
        0.93...,  0.93...,  1.     ,  0.93...,  1.      ])

In [39]:
from sklearn.datasets import load_iris

In [40]:
iris = load_iris()

In [47]:
sourcevars.shape

(4999, 14)

In [45]:
iris.data.shape

(150, 4)